# Generated by Django 2.0 on 2020-01-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(default='If you select yes/no, form will be automatically filled'),
        ),
    ]
